export const THEME_SCALES = {
	color: [
		"page",
		"group",
		"group-inset",
		"line",
		"fill",
		"fill-hover",
		"raise",
		"edge",
		"ink",
		"muted",
		"accent",
		"success",
		"warning",
		"error",
		"info",
		"note",
		"standout",
		"highlight",
		"accent-wash",
		"success-wash",
		"warning-wash",
		"error-wash",
		"info-wash",
		"note-wash",
		"standout-wash",
		"highlight-wash",
		"red",
		"orange",
		"yellow",
		"green",
		"cyan",
		"blue",
		"purple",
		"pink",
	],
	text: ["xs", "sm", "base", "lg", "h6", "h5", "h4", "h3", "h2", "h1"],
	font: ["sans", "mono"],
	"font-weight": ["normal", "medium", "semibold", "bold"],
	radius: ["plate", "item", "pill"],
	spacing: ["items", "parts", "cards", "plate"],
	shadow: ["raise", "glass"],
	ease: ["spring", "standard"],
};
